# builds the content of https://github.com/rectorphp/rector-prefixed
# inspiration from https://github.com/phpstan/phpstan-src/blob/master/.github/workflows/phar.yml
name: Packages Tests

on:
    pull_request: null
    push:
        branches:
            - main

env:
    # see https://github.com/composer/composer/issues/9368#issuecomment-718112361
    COMPOSER_ROOT_VERSION: "dev-main"

jobs:
    packages_tests:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        strategy:
            fail-fast: false
            matrix:
                repository_name:
                    # must be repository name, e.g. https://github.com/rectorphp/rector-nette
                    - rectorphp/rector-symfony
                    - rectorphp/rector-phpunit
                    - rectorphp/rector-doctrine
                    - rectorphp/rector-laravel
                    - rectorphp/rector-nette
                    - rectorphp/rector-cakephp
                    - rectorphp/rector-phpoffice
                    - sabbelasichon/typo3-rector

        steps:
            # see https://github.com/actions/checkout#usage
            -
                uses: "actions/checkout@v2"
                with:
                    repository: ${{ matrix.repository_name }}
                    ref: "main"

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer config minimum-stability dev

            # test with current commit in a pull-request
            -
                run: composer require rector/rector-src dev-main#${{github.event.pull_request.head.sha}} --no-update
                if: ${{ github.event_name == 'pull_request' }}

<<<<<<< HEAD
<<<<<<< HEAD
=======
            # use PHPStan 1.0
            -
                run: composer require phpstan/phpstan "1.0.x-dev as 0.12.99" --no-update
                if: ${{ github.event_name == 'pull_request' }}

>>>>>>> abd995e94... ThisType needs reflection
=======
            # use PHPStan 1.0
            -
                run: composer require phpstan/phpstan 1.0.x-dev as 0.12.99 --dev --no-install
                if: ${{ github.event_name == 'pull_request' }}

>>>>>>> 8c175bebc... [CI] use PHPStan 1 for packages too
            -   run: composer install --ansi

            -   run: vendor/bin/phpunit
